### ISSUE TITLE
NEXT-10847 - Overview and basic management of scheduled tasks from the administration

### ISSUE THREAD

**Issue by felixbrucker** [shopwareBoostDay/platform#104]
**Description**  

Currently there is no way to see and manage scheduled tasks except for looking at the database itself. As a first step one can list all scheduled tasks and add the possiblity to modify next execution time, change the interval and status, similar to how it was possible in SW5.

**Comment by shyim** [comment]
As example how it can be implemented :) https://github.com/FriendsOfShopware/FroshTools/tree/master/src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-scheduled
