### ISSUE TITLE
Add (state) filter sidebar to order list view

### ISSUE THREAD

**Issue by hanneswernery** [shopwareBoostDay/platform#107]
**Description**  
The order list view can only be filtered by affiliate code and campaign code which is not enough for most users.
<img width="2254" alt="Screenshot 2020-09-09 at 15 31 16" src="https://user-images.githubusercontent.com/12038224/92605371-f0b8d680-f2b1-11ea-9263-4992039f9c8b.png">

We already implemented a sidebar-order-filter (by states) in our "orders" tab of the product detail view in our _Pickware ERP Starter_ plugin:
<img width="1723" alt="Screenshot 2020-09-09 at 13 48 17" src="https://user-images.githubusercontent.com/12038224/92595262-5dc56f80-f2a4-11ea-98a3-1120d78e7749.png">
Hence we could implement this feature for the order list view as well.

**Example**  
Take a look at the order list view (`/admin/sw/order/index`) and compare it to the "orders" tab of any product in our demo shop that has _Pickware ERP Starter_ installed: https://sw6demo.pickware.de/admin

There are already some issues about this:
https://issues.shopware.com/issues/NEXT-10480
https://issues.shopware.com/issues/NEXT-9261
https://issues.shopware.com/issues/NEXT-7375

**Comment by hanneswernery** [comment]
I just updated the issue title and screenshot to match the current state of `showpare/platform`.

**Comment by mitelg** [comment]
on the last boostday there was a similar topic for the product list

the outcome was to build a general filter sidebar which could be used in all modules

https://github.com/shopware/platform/issues/880 (for second boostday: https://github.com/shopwareBoostDay/platform/issues/55
https://github.com/shopware/platform/pull/948

**Comment by hanneswernery** [comment]
> to build a general filter sidebar

Are you suggesting that the current components (`sw-sidebar`, `sw-sidebar-item` with some select fields) should be combined in a general "filter sidebar" component that uses a unified interface (`props`, events) in all list views while the actual filter elements (select fields) vary from view to view?

**Comment by mitelg** [comment]
yeah basically. like I already stated here: https://github.com/shopware/platform/issues/880#issuecomment-627400506

I'm not a frontend guy, so I don't know how easy/hard this is :smile:

**Comment by hanneswernery** [comment]
Nothing is impossible 🌈 🙌

**Comment by MarcelSchmaeing** [comment]
Hi,

thanks for the really great contribution idea. 
We plan to implement filters for the product, customer and order module in the near future. I just want to avoid that we put in double work here. 

Many greetings,

Marcel

**Comment by hanneswernery** [comment]
Allright! I will close this issue then.
