### ISSUE TITLE
NEXT-1797 - execute composer require on plugin install

### ISSUE THREAD

**Issue by mitelg** [shopwareBoostDay/platform#111]
**Description**  
Composer 2.0 is in RC phase now. A good time to finish the plugin installation how it was one meant to be.
Having already this bad boy 
https://github.com/shopware/platform/blob/master/src/Core/Framework/Plugin/Composer/CommandExecutor.php
which of course needs some love. 

it is also not the best solution to execute the whole command, imo. but unfortunately the composer commands contain much logic. 
maybe it is possible to extract only the needed things. so that we could have nice exception handling instead of parsing the string output of the command for errors, for example.

we also need the counter part on plugin uninstall.

additionally we need some benchmarks. composer 2 is amazingly fast, but on slow connections the downloading of packages takes some times which will probably lead to timeout issues if the plugin installation is triggered in the adminstration.

first steps, which I already could provide: https://github.com/mitelg/platform/tree/next-1797/composer-2-compatibility
- updating composer dependencies in our `composer.json`
- method for executing `composer remove`
- exceptions which show the buffered output, if the exit code was not `0`

checks needed:
- performance
- system has still composer 1.x but Shopware has already above code

It would make me happy, if some of you are willing to help here 🤗💙 I will give support as much as I can

Tickets:
- https://issues.shopware.com/issues/NEXT-1797
- https://issues.shopware.com/issues/NEXT-10745

**Comment by windaishi** [comment]
I tried this with one of our plugins and it worked well. Nice Job. Installing a plugin took about 10 second via the Administration.

**Comment by windaishi** [comment]
Unfortunately I cant execute `composer install` for your platform-branch with Composer 2.0.0-RC1. Seems like some packages in the dependency tree of `shopware/platform` are not compatible with PHP7.2 and Composer 2.

```
10:05 $ composer update
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - ocramius/package-versions[1.1.1, ..., 1.2.0] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - ocramius/package-versions[1.3.0, ..., 1.4.2] require composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - ocramius/package-versions[1.5.0, ..., 1.5.1] require php ^7.3.0 -> your php version (7.2.9; overridden via config.platform, actual: 7.4.8) does not satisfy that requirement.
    - ocramius/package-versions[1.6.0, ..., 1.9.0] require php ^7.4.0 -> your php version (7.2.9; overridden via config.platform, actual: 7.4.8) does not satisfy that requirement.
    - ocramius/proxy-manager[2.3.0, ..., 2.5.2] require php ^7.4.0 -> your php version (7.2.9; overridden via config.platform, actual: 7.4.8) does not satisfy that requirement.
    - ocramius/package-versions[1.10.0, ..., 1.11.0] require php ^7.4.7 -> your php version (7.2.9; overridden via config.platform, actual: 7.4.8) does not satisfy that requirement.
    - ocramius/proxy-manager[2.6.0, ..., 2.7.0] require php 7.4.* -> your php version (7.2.9; overridden via config.platform, actual: 7.4.8) does not satisfy that requirement.
    - ocramius/proxy-manager 2.7.1 requires php 7.4.0 -> your php version (7.2.9; overridden via config.platform, actual: 7.4.8) does not satisfy that requirement.
    - ocramius/proxy-manager[2.8.0, ..., 2.9.1] require php ~7.4.1 -> your php version (7.2.9; overridden via config.platform, actual: 7.4.8) does not satisfy that requirement.
    - symfony/proxy-manager-bridge v4.4.13 requires ocramius/proxy-manager ~2.1 -> satisfiable by ocramius/proxy-manager[2.1.0, ..., 2.9.1].
    - ocramius/proxy-manager[2.2.0, ..., 2.2.3] require ocramius/package-versions ^1.1.3 -> satisfiable by ocramius/package-versions[1.1.3, ..., 1.11.0].
    - ocramius/proxy-manager[2.1.0, ..., 2.1.1] require ocramius/package-versions ^1.1.1 -> satisfiable by ocramius/package-versions[1.1.1, ..., 1.11.0].
    - Root composer.json requires symfony/proxy-manager-bridge ~4.4.13 -> satisfiable by symfony/proxy-manager-bridge[v4.4.13].
ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
If you can not upgrade PHP you can require composer/package-versions-deprecated to resolve this with PHP 7.0+.
You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-req=composer-plugin-api, but this may result in broken plugins and bigger problems down the line.
```
