### ISSUE TITLE
NEXT-10918 - Support for autowiring of entity repositories

### ISSUE THREAD

**Issue by soebbing** [shopwareBoostDay/platform#131]
**Description**  
The Symfony service autowiring is an awesome way of minimizing the configuration overhead of plugging your services together for the DIC. Currently this is made impossible in part due to the automated repositories generated for for the defined entities in the DAL.

**Example**  
It should be possible to have the Symfony DIC autowire repositories based on the requested interface and variable name of an argument, e.g. `public function __construct(EntityRepositoryInterface $productRepository)` should inject the service with the id `product.repository`.

**Comment by Sironheart** [comment]
I'd be interested in doing this in cooperation :)
