### ISSUE TITLE
Filter in the administration should be preserved on a page reload

### ISSUE THREAD

**Issue by Sironheart** [shopwareBoostDay/platform#247]
Currently, when reloading a page in the administration (for example in the media module) the filter gets lost.

Steps to reproduce:
- Open the media module in the administration 
- Select a filter (for example select a different sorting)
- Reload the page (with pressing f5, ctrl + r or cmd+r)
- The selected filter is lost.

**Comment by rherwig** [comment]
The primary issue is that - unlike in data tables (like products view) - the sorting is not reflected in the URL.

There is a mixin that does that for the data tables in the administration, which can be seen here:
https://github.com/shopwareBoostDay/platform/blob/trunk/src/Administration/Resources/app/administration/src/app/mixin/listing.mixin.js

My idea would be to implement a similar mixin for the purpose of adding filter parameters to the URL for filters besides data tables. The challenge imo is, to code it DRY and thus find a sensible way to share code between the `listing.mixin` and the potential new one.

Any opinions on that?
