### ISSUE TITLE
CheckoutOrderPlacedEvent should also include current cart or SalesChannelContext

### ISSUE THREAD

**Issue by SRaromicon** [shopwareBoostDay/platform#248]
**Description**
Right now, when CheckoutOrderPlacedEvent is dispatched it only includes newly created order and context object. So it's not possible to copy data from cart to order like additional data saved in an extension of cart or additional data on LineItems.
SalesChannelContext is also not provided, so it's not possible to load the current cart by your own.
It might be extremly helpful to get also current cart. Extending this event could be made without any breaking changes.

**Comment by shyim** [comment]
Why should it contain the cart? It's empty at that time, cause it's converted to the Cart.

**Comment by SRaromicon** [comment]
It's not empty at this point. It's quite before the cart get's deleted. Otherwise how can we copy data to order customFields from cart, which is saved at cart as an extension and based on user input?
Right now i'm using this event to copy this data, but it's really difficult to load the cart. I'm using the request stack, getting the master request, fetching the sales channel context object, retrieving the token and loading the cart.

**Comment by shyim** [comment]
You can use better the CartConvertedEvent: https://github.com/shopware/platform/blob/84c0dcd5e5021ebb16e9870aa89a50afea268bce/src/Core/Checkout/Cart/Order/OrderConverter.php#L200

**Comment by SRaromicon** [comment]
I have tried to use that Event, but it got never triggered my subscriber. This event seems to be an event for the "App" Webhooks? How can i subscribe to those type of events without using a webhook?

**Comment by shyim** [comment]
Its a normal event

**Comment by SRaromicon** [comment]
Sorry for the hassle. I have checked the event again, and it' working fine. Issue can be closed.
