### ISSUE TITLE
Support composer/installer in Enterprise Modules

### ISSUE THREAD

**Issue by FloKnapp** [shopwareBoostDay/platform#274]
**Description**  
In order to make it possible to install the Shopware Enterprise CMS-Modules via Composer, i must be able to determine the install paths of the plugin. This can be achieved with the Composer Package `composer/installer`. 

The Author of the Package (in this case, Shopware) must include that Dependency in his `composer.json`. As a Developer, i'm then able to configure the desired installation paths for each Plugin separately.

**Example**
Given i'm about to install the B2BPlatform-Module. The `require` Section of the `composer.json` would look as follows:
```
//...
"require": {
        "composer/installer": "^v1.10.0",
        "nikic/fast-route": "^1.0",
        "phpoffice/phpspreadsheet": "^1.14",
        "shopware/dbal-nested-set": "^1.2.2",
        "ext-intl": "*",
        "ext-json": "*",
        "ext-pdo": "*"
    }
//...
```

I'm then able to do the following in my `composer.json`:
```
//...
{
    "extra": {
        "installer-paths": {
            "custom/plugin/{$name}/": ["type:shopware-platform-plugin"]
        }
    }
}
//...
```
Currently the B2BPlatform-Package contains the type `shopware-platform-plugin` which isn't supported by `composer/installer` yet. I'll try to contribute a solution to the Author of `composer/installer`.

**Comment by mitelg** [comment]
hey @FloKnapp 
the plugin does not need to be installed under "custom/plugins".
Shopware will also recognise plugins which are installed in the normal vendor directory

**Comment by FloKnapp** [comment]
Hi @mitelg 
thank you for your quick reply. I think i misunderstood the interaction between Shopware and Composer. I assumed that every Plugin has it's own `vendor`, as said "B2bPlatform"-Package comes with it's own `vendor`-Folder already integrated. 

In my case it caused a double declarated function which prevented my Application to start. I had to get rid of the integrated `vendor`-Folder in order to make it work.

I just heard from a colleague that there is a change in Shopware coming, regarding the level of interaction with Composer from the Plugin's context. It sounds like that would address exactly my issue:
https://github.com/shopware/platform/blob/trunk/src/Docs/Resources/current/60-references-internals/40-plugins/020-plugin-base-class.md#executecomposercommands

Thank you again for your quick answer and clarification.

**Comment by mitelg** [comment]
yes, this will be part of the upcoming 6.4.0.0

so the issue could be closed? 🙂
