### ISSUE TITLE
NEXT-14171 - Add a sitemap sales channel event

### ISSUE THREAD

**Issue by shyim** [shopwareBoostDay/platform#300]
Some extensions which adds a own sales channel like Shopware Markets needs an event to remove their own sales channel from the sitemap generation

This event should be called inside SitemapGenerateComand and SitemapGenerateTaskHandler

https://issues.shopware.com/issues/NEXT-14171

**Comment by sebi007** [comment]
@shyim Just a short question here. Is it enough to add a new event where you transmit the saleschannels and then in the extension you could say $event->getSalesChannels()->remove(id)?

**Comment by shyim** [comment]
I would pass the criteria to the event. So the caller can modify it
