### ISSUE TITLE
Menü link in neuem Fenster öffnen

### ISSUE THREAD

**Issue by shyim** [shopwareBoostDay/platform#395]
Es wäre sehr nützlich, wenn man einen externen Link im Menü (Katalog - Kategorien - Kategorietyp - Benutzerdefinierter Link) in einem neuen Fenster / Tab öffnen lassen könnte. Das sollte bei den Optionen ausgewählt werden können.

Vgl. hierzu auch diesen Forum Beitrag - https://forum.shopware.com/discussion/comment/287816#Comment_287816

**Comment by rherwig** [comment]
@shyim Looks like, this is already implemented.

![Screenshot](https://cloud-storage.xsplit.com/prd/13716950/01FQ1EWMH8XJM79XDEJFEGPE5C.jpg)

**Comment by shyim** [comment]
Thanks!
