### ISSUE TITLE
Thumbnails of variants use full image size

### ISSUE THREAD

**Issue by shyim** [shopwareBoostDay/platform#427]
*EN:*

Variants have the same photos as the products themselves assigned (2048px).

The thumbnails of the variants use these large images for display and scale the whole thing using HTML instead of responsive picture elements.

This means that a lot of unnecessary data has to be loaded. In our case an article with 24 variants which makes up a few MB in the end.

*DE:*

Varianten haben die gleichen Fotos wie die Produkte selbst zugewiesen (2048px).

Die Thumbnails der Varianten verwenden diese großen Bilder für die Darstellung und skalieren das ganze per HTML statt mit responsive Picture Elementen.

Dadurch müssen extrem viel unnötige Daten geladen werden. In unserem Fall ein Artikel mit 24 Varianten was dann unterm Strich gleich ein paar MB ausmacht.

![https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1587120319_5e9988bf58c94_1587120317_5e9988bd22b7b_Bildschirmfoto%202020-04-17%20um%2012.45.02.png](https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1587120319_5e9988bf58c94_1587120317_5e9988bd22b7b_Bildschirmfoto%202020-04-17%20um%2012.45.02.png)

**Comment by rherwig** [comment]
@shopwareBoostDay/shopware-qa As of the current development version (v6.4.99 Stable Version 99999.9999999), I cannot reproduce the issue. The following screenshot from my locale machine shows the proper usage of a responsive `img` element.

![Savoy Cabbage   Teal   K10R1000 5 - Google Chrome](https://user-images.githubusercontent.com/12065150/146325319-26faea49-7bce-4cf6-a210-0dd99917ebb7.jpg)

The image representation of the variant has been added via assigning a storefront presentation to the respective property, as seen in this screenshot:

![Savoy Cabbage   Products   Shopware Administration - Google Chrome](https://user-images.githubusercontent.com/12065150/146325562-2902cd0e-9e5a-42c2-8bc5-f46ed97c5b5a.jpg)

**Comment by shyim** [comment]
Thanks I will close it also internally
